version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///app.db
      - SECRET_KEY=your-secret-key-change-in-production
    volumes:
      - .:/app
    restart: unless-stopped